[package]
name = "raw_html_rendering"
version = "0.1.0"
edition = "2021"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"

[dependencies]
aes = "0.8.4"
ascii = "1.1.0"
async-channel = { version = "2.3.1", default-features = false }
async-lock = { version = "3.4.0", default-features = false }
async-native-tls = "0.5.0"
async-net = { version = "2.0.0", default-features = false }
async-task = { version = "4.7.1", default-features = false }
cbc = { version = "0.1.2", features = ["std"] }
dotenv = { version = "0.15.0", default-features = false }
futures-lite = { version = "2.3.0", default-features = false }
gtk = "0.18.1"
jsonwebtoken = { version = "9.3.0", default-features = false }
maud = "0.26.0"
md5 = "0.7.0"
once_cell = "1.19.0"
openssl = { version = "0.10.66", features = ["vendored"] }
rand = { version = "0.8.5", default-features = false }
rusqlite = { version = "0.32.1", default-features = false, features = ["time"] }
serde = { version = "1.0.209", features = ["derive", "rc"] }
serde_json = "1.0.127"
serde_urlencoded = "0.7.1"
smol-timeout = "0.6.0"
smolscale = { version = "0.4.11", default-features = false }
time = { version = "0.3.36", default-features = false, features = ["macros", "serde", "serde-well-known", "std"] }
tiny_http = "0.12.0"
webkit2gtk = "2.0.1"

[dev-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["std", "std_rng"] }
